// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  translation: {
    admin: {
      members: {
        added: 'Agregado: {{date}}';
        empty: 'Todavía no hay miembros en la beta.';
        noMatch: 'Ningún miembro coincide con la búsqueda.';
        revoke: 'Revocar';
        revokeDialog: {
          description: '{{email}} dejará de tener acceso a la beta en su próximo gate (no borra su cuenta ni sus datos). Podés volver a invitarlo aprobando una nueva solicitud.';
          title: '¿Revocar el acceso?';
        };
        searchAria: 'Buscar miembros por email';
      };
      requests: {
        approve: 'Aprobar';
        empty: 'No hay solicitudes pendientes.';
        noMatch: 'Ninguna solicitud coincide con la búsqueda.';
        reject: 'Rechazar';
        searchAria: 'Buscar solicitudes por email';
      };
      searchByEmail: 'Buscar por email…';
      subtitle: 'Procesá solicitudes de acceso y gestioná los miembros de la beta.';
      tabs: {
        members: 'Miembros';
        requests: 'Solicitudes';
      };
      title: 'Administración';
    };
    auth: {
      accessRequest: {
        betaTagline: 'Beta cerrada por invitación';
        invalidEmail: 'Ingresá un email válido.';
        motivo: 'Motivo';
        optional: '(opcional)';
        pageSubtitle: 'Dejanos tu email y, si hay lugar, sumamos tu cuenta a la beta.';
        pageTitle: 'Solicitar acceso';
        placeholder: 'Contanos para qué querés usar SecondMind';
        submit: 'Solicitar acceso';
        success: 'Recibimos tu solicitud. Cuando se habilite tu acceso vas a poder iniciar sesión normalmente.';
      };
      action: {
        invalidBody: 'Este enlace no es válido o está incompleto. Pedí uno nuevo desde la app.';
        invalidTitle: 'Enlace inválido';
        reset: {
          errorTitle: 'No pudimos restablecer tu contraseña';
          forAccount: 'Para la cuenta <1>{{email}}</1>.';
          formTitle: 'Elegí una nueva contraseña';
          loadingBody: 'Un segundo, estamos verificando tu enlace de recuperación.';
          loadingTitle: 'Validando el enlace…';
          newPassword: 'Nueva contraseña';
          submit: 'Cambiar contraseña';
          successBody: 'Ya podés iniciar sesión con tu nueva contraseña.';
          successTitle: 'Contraseña actualizada';
        };
        unsupportedBody: 'Este tipo de enlace no está disponible. Pedí uno nuevo desde la app.';
        unsupportedTitle: 'Enlace no soportado';
        verify: {
          errorTitle: 'No pudimos verificar tu email';
          loadingBody: 'Un segundo, estamos activando tu cuenta.';
          loadingTitle: 'Verificando tu email…';
          successBody: 'Tu cuenta está activa. Ya podés iniciar sesión.';
          successTitle: 'Email verificado';
        };
      };
      backToSignIn: 'Volver al inicio de sesión';
      confirmPassword: 'Confirmar contraseña';
      continueWithGoogle: 'Continuar con Google';
      creatingAccount: 'Creando cuenta…';
      email: 'Email';
      forgotPassword: '¿Olvidaste tu contraseña?';
      noAccess: '¿No tenés acceso?';
      orContinueWith: 'o continuá con';
      password: 'Contraseña';
      passwordHint: 'Mínimo 8 caracteres con al menos un número.';
      requestInvite: 'Solicitá una invitación';
      reset: {
        send: 'Enviar enlace';
        sentBody: 'Si la cuenta existe, recibirás un enlace en tu email para restablecer tu contraseña.';
        sentTitle: 'Revisá tu correo';
        subtitle: 'Te enviaremos un enlace para restablecer tu contraseña.';
        title: 'Recuperar contraseña';
      };
      signIn: 'Iniciar sesión';
      signUp: 'Crear cuenta';
      signingIn: 'Iniciando sesión…';
      signupGate: {
        checking: 'Verificando disponibilidad…';
        disabled: 'Registro deshabilitado temporalmente';
        disabledBody: 'Volvé más adelante o iniciá sesión con Google si ya tenés cuenta.';
        error: 'No se pudo verificar disponibilidad. Reintentá.';
      };
      tagline: 'Tu segundo cerebro digital';
      validation: {
        emailInvalid: 'Email inválido.';
        minChars: 'Mínimo 8 caracteres.';
        passwordMismatch: 'Las contraseñas no coinciden.';
      };
      verify: {
        autoRefresh: '¿Ya verificaste? Esta página se actualiza sola cuando volvés desde tu correo.';
        bannerMessage: 'Verificá tu email para asegurar tu cuenta.';
        body: 'Para activar tu cuenta verificá <1>{{email}}</1>. Revisá tu bandeja de entrada y la carpeta de spam, y hacé click en el enlace — sin verificación no podés guardar notas ni tareas. ¿No te llegó? Reenvialo abajo.';
        pageTitle: 'Verificá tu email para continuar';
        resend: 'Reenviar enlace';
        sent: 'Enviado · {{seconds}}s';
      };
    };
    capture: {
      fabLabel: 'Captura rápida';
      hint: {
        cancel: 'cancelar';
        close: 'cerrar';
        newLine: 'línea nueva';
        save: 'guardar';
      };
      placeholder: 'Escribe una idea...';
      title: 'Captura rápida';
      unauth: {
        message: 'Abrí SecondMind para iniciar sesión.';
        open: 'Abrir SecondMind';
      };
    };
    changelog: {
      dismiss: 'Entendido';
      history: {
        back: 'Ajustes';
        description: 'Lo nuevo de cada versión, lo más reciente primero.';
        title: 'Historial de novedades';
      };
      v052: {
        items: [
          'Estrenas este panel de novedades: tras cada actualización con cambios visibles, te mostramos aquí lo nuevo, una sola vez.',
          'La versión que estás usando ahora se ve en Ajustes → Información de la app, en escritorio, web y Android.',
        ];
        title: 'Novedades de la 0.5.2';
      };
      v053: {
        items: [
          'Ahora puedes agregar tablas a tus notas: insértalas desde el menú de comandos del editor, suma o quita filas y columnas, marca encabezados, alinea el texto y combina celdas.',
          'El historial de novedades llegó a Ajustes → Historial de novedades: repasa lo nuevo de cada versión cuando quieras.',
        ];
        title: 'Novedades de la 0.5.3';
      };
    };
    commandPalette: {
      actions: 'Acciones';
      closeSplit: 'Cerrar panel derecho';
      groups: {
        notes: 'Notas';
        projects: 'Proyectos';
        tasks: 'Tareas';
      };
      hideSidebar: 'Ocultar sidebar';
      noResults: 'Sin resultados para “{{query}}”';
      open: 'Abrir buscador';
      openSplit: 'Abrir nota lado a lado';
      placeholder: 'Buscar notas, tareas, proyectos...';
      recent: 'Recientes';
      showSidebar: 'Mostrar sidebar';
      title: 'Buscar';
      trigger: 'Buscar…';
    };
    common: {
      activeBadge: 'activo';
      avatar: 'Avatar';
      cancel: 'Cancelar';
      close: 'Cerrar';
      create: 'Crear';
      creating: 'Creando...';
      retry: 'Reintentar';
      save: 'Guardar';
      saving: 'Guardando…';
      sending: 'Enviando…';
      unlink: 'Desvincular';
      untitled: 'Sin título';
    };
    dashboard: {
      greeting: {
        afternoon: 'Buenas tardes, {{name}}';
        fallbackName: 'hola';
        morning: 'Buenos días, {{name}}';
        night: 'Buenas noches, {{name}}';
      };
      habitsToday: {
        progress: 'Progreso';
        seeWeek: 'Ver semana →';
        title: 'Hábitos de hoy';
      };
      hubs: {
        connections: 'Hub: {{total}} conexiones';
        empty: 'Linkea notas escribiendo @ — los hubs aparecerán acá.';
        title: 'Hubs activos';
      };
      inbox: {
        empty: 'Inbox limpio 🎉';
        process: 'Procesar →';
        requiresConnection: 'Requiere conexión a internet';
        title: 'Inbox';
      };
      projects: {
        empty: 'Sin proyectos activos';
        noPendingTasks: 'Sin tareas pendientes';
        pendingTasks_many: '{{count}} tareas pendientes';
        pendingTasks_one: '{{count}} tarea pendiente';
        pendingTasks_other: '{{count}} tareas pendientes';
        seeAll: 'Ver todos →';
        seeProjects: 'Ver proyectos →';
        title: 'Proyectos activos';
      };
      recentNotes: {
        createFirst: 'Crear primera nota →';
        empty: 'No tenés notas todavía.';
        seeAll: 'Ver todas →';
        title: 'Notas recientes';
      };
      review: {
        empty: 'Nada que repasar hoy. Vuelve mañana o crea más notas para activar la revisión.';
        seeAll: 'Ver todas las {{total}}';
        titleEmpty: 'Por revisar';
        title_many: 'Te tocan {{count}} notas hoy.';
        title_one: 'Te toca {{count}} nota hoy.';
        title_other: 'Te tocan {{count}} notas hoy.';
      };
      tasks: {
        completeAria: 'Completar {{name}}';
        empty: 'Nada para hoy 🎉';
        seeAll: 'Ver todas →';
        title: 'Tareas de hoy';
      };
    };
    editor: {
      backlinks: {
        empty: 'Sin backlinks aún. Las notas que enlacen a esta aparecerán acá.';
        hide: 'Ocultar backlinks';
      };
      codeBlock: {
        copied: 'Código copiado';
        copy: 'Copiar código';
      };
      distill: {
        banner: {
          l1: 'Subiste a L1 · Pasajes clave marcados';
          l2: 'Subiste a L2 · Esenciales resaltados';
          l3: 'Llegaste a L3 · Nota destilada';
        };
        indicatorLabel: 'Nivel de destilación: L{{level}} — {{label}}';
        l0: {
          label: 'Sin destilación';
          tip: 'Selecciona los pasajes clave y aplícales negrita (Ctrl+B) para marcarlos como L1.';
        };
        l1: {
          label: 'Pasajes clave marcados';
          tip: 'De lo que marcaste, resalta lo verdaderamente esencial con Ctrl+Shift+H para subir a L2.';
        };
        l2: {
          label: 'Esenciales resaltados';
          tip: 'Escribe un resumen ejecutivo en tus palabras para subir a L3 — la nota queda lista para tu yo del futuro, sin tener que releer todo.';
        };
        l3: {
          label: 'Resumen escrito';
          tip: 'Destilación completa. La nota está lista para tu yo del futuro.';
        };
        writeL3: 'Escribir resumen L3';
      };
      link: {
        confirm: 'Confirmar link';
        edit: 'Editar link';
        openNewTab: 'Abrir link en nueva pestaña';
      };
      menu: {
        noResults: 'Sin resultados';
        noResultsQuery: 'Sin resultados para "{{query}}"';
      };
      placeholder: 'Escribe una idea...';
      review: {
        activate: 'Activar revisión periódica';
        again: 'Necesito repasarla';
        good: 'La recuerdo bien';
        next: 'Próxima revisión: {{when}}';
        prompt: '¿La recordás?';
        relative: {
          days_many: 'en {{count}} días';
          days_one: 'en {{count}} día';
          days_other: 'en {{count}} días';
          months_many: 'en {{count}} meses';
          months_one: 'en {{count}} mes';
          months_other: 'en {{count}} meses';
          today: 'hoy';
          tomorrow: 'mañana';
          weeks_many: 'en {{count}} semanas';
          weeks_one: 'en {{count}} semana';
          weeks_other: 'en {{count}} semanas';
        };
        reviewed: 'Revisado. Próxima revisión: {{when}}';
        soon: 'pronto';
      };
      save: {
        error: 'Error al guardar';
        retrying: 'Reintentando...';
        saved: 'Guardado';
        saving: 'Guardando...';
      };
      saveError: {
        copied: 'Copiado';
        copy: 'Copiar contenido';
        detail: 'Reintentamos 3 veces sin éxito. Reintentar guarda el contenido completo. Descartar revierte el título visible.';
        discard: 'Descartar cambios';
        title: 'No pudimos guardar tu última edición';
      };
      similar: {
        empty: 'Sin notas similares aún.';
        noEmbedding: 'Guarda la nota para ver sugerencias.';
        offline: 'Disponible cuando vuelva la conexión.';
        title: 'Notas similares';
      };
      slash: {
        category: {
          blocks: 'Bloques';
          lists: 'Listas';
          mentions: 'Menciones';
          templates: 'Plantillas';
          text: 'Texto';
        };
        items: {
          blockquote: {
            description: 'Cita textual';
            label: 'Blockquote';
          };
          bulletList: {
            description: 'Lista con viñetas';
            label: 'Bullet List';
          };
          codeBlock: {
            description: 'Bloque de código';
            label: 'Code Block';
          };
          divider: {
            description: 'Línea horizontal';
            label: 'Divider';
          };
          heading1: {
            description: 'Título principal';
            label: 'Heading 1';
          };
          heading2: {
            description: 'Subtítulo';
            label: 'Heading 2';
          };
          heading3: {
            description: 'Subtítulo menor';
            label: 'Heading 3';
          };
          mentionNote: {
            description: 'Insertar @ para autocompletar';
            label: 'Mencionar nota';
          };
          orderedList: {
            description: 'Lista numerada';
            label: 'Numbered List';
          };
          table: {
            description: 'Tabla de filas y columnas';
            label: 'Table';
          };
          taskList: {
            description: 'Lista con checkboxes';
            label: 'Task List';
          };
          templateLiterature: {
            description: 'Template para notas de fuentes';
            label: 'Nota Literature';
          };
          templatePermanent: {
            description: 'Template para ideas permanentes';
            label: 'Nota Permanent';
          };
        };
      };
      suggestion: {
        regionLabel: 'Sugerencias de la AI';
      };
      summaryL3: {
        placeholder: '¿Qué le explicarías a tu yo del futuro sobre esto? 1-2 frases.';
        title: 'Resumen ejecutivo (L3)';
      };
      table: {
        addColumnAfter: 'Insertar columna a la derecha';
        addColumnBefore: 'Insertar columna a la izquierda';
        addRowAfter: 'Insertar fila abajo';
        addRowBefore: 'Insertar fila arriba';
        alignCenter: 'Centrar';
        alignLeft: 'Alinear a la izquierda';
        alignRight: 'Alinear a la derecha';
        deleteColumn: 'Eliminar columna';
        deleteRow: 'Eliminar fila';
        deleteTable: 'Eliminar tabla';
        mergeOrSplit: 'Combinar o dividir celdas';
        toggleHeaderColumn: 'Columna de encabezado';
        toggleHeaderRow: 'Fila de encabezado';
      };
      templates: {
        literature: {
          inMyWordsHeading: 'En mis palabras';
          interpretationPlaceholder: '[Tu interpretación y conexiones]';
          keyIdeasHeading: 'Ideas clave';
          sourceHeading: 'Fuente';
          sourcePlaceholder: '[Autor, título, año, URL]';
        };
        permanent: {
          connectionsHeading: 'Conexiones';
          connectionsPlaceholder: '[Notas relacionadas — usa @ para mencionar]';
          developmentHeading: 'Desarrollo';
          developmentPlaceholder: '[Argumentación, evidencia, ejemplos]';
          thesisHeading: 'Tesis';
          thesisPlaceholder: '[La idea central en una oración]';
        };
      };
      toolbar: {
        bold: 'Negrita';
        code: 'Código inline';
        highlight: 'Resaltar';
        italic: 'Cursiva';
        link: 'Link';
        strike: 'Tachado';
      };
      wikilink: {
        untitled: 'Nota sin título';
      };
    };
    entities: {
      area: {
        conocimiento: 'Conocimiento';
        finanzas: 'Finanzas';
        habitos: 'Hábitos';
        pareja: 'Pareja';
        proyectos: 'Proyectos';
        salud: 'Salud y Ejercicio';
      };
      discardable: {
        group: {
          habit: 'Hábitos';
          inboxItem: 'Inbox';
          note: 'Notas';
          objective: 'Objetivos';
          project: 'Proyectos';
          task: 'Tareas';
        };
        habitFallback: 'Hábitos ({{id}})';
        habitOfDate: 'Hábitos del {{date}}';
        inboxEmpty: 'Item sin contenido';
        noteUntitled: 'Nota sin nombre';
        objectiveUntitled: 'Objetivo sin nombre';
        projectUntitled: 'Proyecto sin nombre';
        taskUntitled: 'Tarea sin nombre';
      };
      habit: {
        codear: 'Codear';
        comerBien: 'Comer bien';
        ejercicio: 'Ejercicio';
        estirar: 'Estirar';
        gratitud: 'Gratitud';
        ingles: 'Inglés';
        leer: 'Leer';
        madrugar: 'Madrugar';
        meditar: 'Meditar';
        noComerDulce: 'No comer dulce';
        pareja: 'Pareja';
        planificarDia: 'Planificar día';
        tenderCama: 'Tender cama';
        tomarAgua: 'Tomar agua';
      };
      inboxResultType: {
        note: 'Nota';
        project: 'Proyecto';
        task: 'Tarea';
        trash: 'Descartar';
      };
      noteType: {
        fleeting: 'Fugaz';
        literature: 'Literatura';
        permanent: 'Permanente';
      };
      objectiveStatus: {
        completed: 'Completado';
        inProgress: 'En progreso';
        notStarted: 'No empezado';
      };
      paraType: {
        archive: 'Archivo';
        area: 'Área';
        project: 'Proyecto';
        resource: 'Recurso';
      };
      pendingSync: {
        habit: {
          plur: 'hábitos';
          sing: 'hábito';
        };
        inboxItem: {
          plur: 'items de inbox';
          sing: 'item de inbox';
        };
        note: {
          plur: 'notas';
          sing: 'nota';
        };
        noteEdit: {
          plur: 'ediciones de nota';
          sing: 'edición de nota';
        };
        noteNew: {
          plur: 'notas nuevas';
          sing: 'nota nueva';
        };
        objective: {
          plur: 'objetivos';
          sing: 'objetivo';
        };
        objectiveNew: {
          plur: 'objetivos nuevos';
          sing: 'objetivo nuevo';
        };
        project: {
          plur: 'proyectos';
          sing: 'proyecto';
        };
        projectNew: {
          plur: 'proyectos nuevos';
          sing: 'proyecto nuevo';
        };
        task: {
          plur: 'tareas';
          sing: 'tarea';
        };
        taskNew: {
          plur: 'tareas nuevas';
          sing: 'tarea nueva';
        };
      };
      priority: {
        high: 'Alta';
        low: 'Baja';
        medium: 'Media';
        urgent: 'Urgente';
      };
      priorityLong: {
        high: 'Prioridad alta';
        low: 'Prioridad baja';
        medium: 'Prioridad media';
        urgent: 'Prioridad urgente';
      };
      projectStatus: {
        group: {
          completed: 'Completados';
          inProgress: 'En progreso';
          inbox: 'Sin clasificar';
          notStarted: 'No empezados';
          onHold: 'En pausa';
        };
        option: {
          completed: 'Completado';
          inProgress: 'En progreso';
          inbox: 'Inbox';
          notStarted: 'No empezado';
          onHold: 'En pausa';
        };
      };
    };
    errors: {
      accessCheckUnavailable: 'No pudimos verificar tu acceso. Reintentá en un momento.';
      accountDisabled: 'Esta cuenta está deshabilitada.';
      accountExists: 'Ya existe una cuenta con este email. Probá iniciar sesión o usar Google.';
      actionExpired: 'El enlace expiró. Pedí uno nuevo.';
      actionInvalid: 'El enlace no es válido. Pedí uno nuevo.';
      actionNetworkError: 'Hubo un problema de conexión. Reintentá.';
      adminUnauthorized: 'No autorizado.';
      betaFull: 'Beta llena ({{max}}). Subí el límite o revocá un miembro antes de aprobar.';
      betaFullNoMax: 'Beta llena. Subí el límite o revocá un miembro antes de aprobar.';
      betaUnauthorized: 'Tu cuenta todavía no tiene acceso a la beta. Podés solicitarlo más abajo.';
      default: 'Algo salió mal. Intentá de nuevo.';
      emailUnverified: 'Verificá tu email para continuar.';
      invalidCredentials: 'Email o contraseña incorrectos.';
      invalidEmail: 'Email inválido.';
      invalidInput: 'Datos inválidos. Probá de nuevo.';
      invalidProvider: 'Proveedor no soportado.';
      networkError: 'Sin conexión. Verificá tu internet.';
      operationFailed: 'No se pudo completar la operación. Probá de nuevo.';
      rateLimited: 'Demasiados intentos. Probá de nuevo más tarde.';
      requestNotFound: 'Solicitud no encontrada.';
      resetGeneric: 'Si la cuenta existe, recibirás un enlace en tu email.';
      saveKeyInvalid: 'La API key es inválida.';
      saveKeyRequired: 'La API key es requerida.';
      saveKeyUnavailable: 'No pudimos validar la key ahora. Probá de nuevo en un momento.';
      submitInvalidEmail: 'Revisá el email ingresado.';
      submitInvalidMotivo: 'El motivo no es válido.';
      tooManyRequests: 'Demasiados intentos. Probá de nuevo en unos minutos.';
      unauthenticated: 'Tenés que iniciar sesión.';
      weakPassword: 'Mínimo 8 caracteres con al menos un número.';
      weakPasswordShort: 'Mínimo 8 caracteres.';
    };
    graph: {
      createNotes: 'Crear notas →';
      empty: {
        filtered: 'Ningún nodo coincide con los filtros.';
        noData: 'El grafo cobra vida con más notas y conexiones.';
      };
      exitFullscreen: 'Salir de pantalla completa';
      filters: {
        active: 'activos';
        allOption: 'Todas';
        area: 'Área';
        minLinks: 'Links min';
        reset: 'Resetear';
        title: 'Filtros';
        type: 'Tipo';
      };
      fullscreen: 'Pantalla completa';
      node: {
        openNote: 'Abrir nota →';
      };
      resetFilters: 'Resetear filtros';
      stats: {
        connections_many: '{{count}} conexiones';
        connections_one: '{{count}} conexión';
        connections_other: '{{count}} conexiones';
        notes_many: '{{count}} notas';
        notes_one: '{{count}} nota';
        notes_other: '{{count}} notas';
      };
    };
    habits: {
      gridHeader: 'Hábito';
      nextWeek: 'Semana siguiente';
      prevWeek: 'Semana anterior';
      title: 'Hábitos';
      today: 'Hoy';
    };
    inbox: {
      aiDisabled: 'La clasificación con IA está desactivada. Configurá tu API key de Anthropic para que el inbox sugiera título, tipo y área automáticamente.';
      batch: {
        acceptAll_many: 'Aceptar {{count}} items';
        acceptAll_one: 'Aceptar {{count}} item';
        acceptAll_other: 'Aceptar {{count}} items';
        accepted_many: '{{count}} aceptados';
        accepted_one: '{{count}} aceptado';
        accepted_other: '{{count}} aceptados';
        failed_many: '{{count}} fallaron';
        failed_one: '{{count}} falló';
        failed_other: '{{count}} fallaron';
        processing: 'Procesando...';
      };
      configure: 'Configurar';
      empty: {
        hint: 'Captura una idea nueva con <kbd>Alt+N</kbd> desde cualquier pantalla.';
        title: 'Inbox limpio 🎉';
      };
      form: {
        area: 'Área';
        createAndNext: 'Crear y siguiente';
        priority: 'Prioridad';
        tags: 'Tags (separados por coma)';
        tagsPlaceholder: 'tag1, tag2, tag3';
        title: 'Título';
        type: 'Tipo';
      };
      highConfidence: 'Alta confianza';
      item: {
        dismiss: 'Descartar';
        processing: 'Procesando con AI...';
        queued: 'En cola — se procesará al reconectar';
        toNote: 'Nota';
      };
      pending_many: '{{count}} pendientes';
      pending_one: '{{count}} pendiente';
      pending_other: '{{count}} pendientes';
      process: 'Procesar';
      processView: {
        back: 'Atrás';
        counter: '{{current}} de {{total}}';
        done: {
          backToDashboard: 'Volver al Dashboard';
          captureHint: 'Captura una idea con Alt+N desde cualquier pantalla.';
          noItems: 'No tenés items pendientes.';
          title: '¡Inbox limpio! 🎉';
        };
        dotAria: 'Item {{current}} de {{total}}';
        exit: 'Salir';
        next: 'Siguiente';
        originalContent: 'Contenido original';
        title: 'Procesando Inbox';
      };
      processed: {
        generic: 'Ya procesado';
        hint: 'Usá → Siguiente para volver a un item pendiente.';
        note: 'Ya procesado como nota';
        project: 'Ya procesado como proyecto';
        task: 'Ya procesado como tarea';
        trash: 'Descartado';
      };
      requiresConnection: 'Requiere conexión a internet';
      review: 'Revisar';
      source: {
        email: 'Email';
        quickCapture: 'Captura rápida';
        shareIntent: 'Compartido';
        voice: 'Voz';
        webClip: 'Web clip';
      };
      suggestion: {
        accept: 'Aceptar';
        edit: 'Editar';
        editTitle: 'Editar sugerencia';
        title: 'Sugerencia AI';
      };
      summary: {
        discarded_many: '{{count}} descartados';
        discarded_one: '{{count}} descartado';
        discarded_other: '{{count}} descartados';
        done: 'Procesaste {{list}}.';
        doneItems_many: 'Procesaste {{count}} items.';
        doneItems_one: 'Procesaste {{count}} item.';
        doneItems_other: 'Procesaste {{count}} items.';
        notes_many: '{{count}} notas';
        notes_one: '{{count}} nota';
        notes_other: '{{count}} notas';
        projects_many: '{{count}} proyectos';
        projects_one: '{{count}} proyecto';
        projects_other: '{{count}} proyectos';
        tasks_many: '{{count}} tareas';
        tasks_one: '{{count}} tarea';
        tasks_other: '{{count}} tareas';
      };
      title: 'Inbox';
    };
    installPrompt: {
      install: 'Instalar';
      message: 'Instalar SecondMind para acceso directo desde tu dispositivo.';
    };
    nav: {
      ariaMain: 'Navegación principal';
      closeMenu: 'Cerrar menú';
      expandMenu: 'Expandir menú';
      items: {
        dashboard: 'Dashboard';
        graph: 'Grafo';
        habits: 'Hábitos';
        inbox: 'Inbox';
        notes: 'Notas';
        objectives: 'Objetivos';
        projects: 'Proyectos';
        settings: 'Ajustes';
        tasks: 'Tareas';
      };
      openMenu: 'Abrir menú';
      sections: {
        execution: 'Ejecución';
        knowledge: 'Conocimiento';
      };
      showMenu: 'Mostrar menú';
      signOut: 'Cerrar sesión';
    };
    notes: {
      card: {
        aiSummaryLabel: 'Resumen generado por IA';
        delete: 'Eliminar nota';
        deleteForever: 'Eliminar para siempre';
        favorite: 'Marcar como favorita';
        hardDelete: {
          description: 'Esta acción no se puede deshacer. La nota, sus embeddings y los links que la mencionan se eliminan para siempre.';
          title: '¿Eliminar esta nota para siempre?';
        };
        purgeDays_many: '{{count}} días';
        purgeDays_one: '{{count}} día';
        purgeDays_other: '{{count}} días';
        purgePending: 'Pendiente';
        restore: 'Restaurar nota';
        softDelete: {
          confirm: 'Mover a papelera';
          description: 'Puedes restaurarla desde Notas → Papelera o eliminarla definitivamente desde ahí.';
          title: '¿Mover esta nota a la papelera?';
        };
        unfavorite: 'Quitar de favoritas';
      };
      detail: {
        loadError: 'Error al cargar la nota: {{message}}';
        notFound: 'Esta nota ya no existe.';
      };
      empty: {
        all: 'No tenés notas todavía.';
        backToAll: 'Volver a todas las notas';
        clearSearch: 'Limpiar búsqueda';
        createFirst: 'Crear primera nota';
        favorites: 'No tenés notas favoritas todavía.';
        review: 'Nada por revisar hoy.';
        reviewFilter: 'No se encontraron notas en revisión.';
        showAll: 'Mostrar todas las notas';
        trash: 'Tu papelera está vacía.';
        trashFilter: 'No se encontraron notas en la papelera.';
      };
      newNote: 'Nueva nota';
      newShort: 'Nueva';
      purgeDialog: {
        description_many: 'Se eliminarán para siempre {{count}} notas, sus embeddings y los links que las mencionan. Esta acción no se puede deshacer.';
        description_one: 'Se eliminarán para siempre {{count}} nota, sus embeddings y los links que las mencionan. Esta acción no se puede deshacer.';
        description_other: 'Se eliminarán para siempre {{count}} notas, sus embeddings y los links que las mencionan. Esta acción no se puede deshacer.';
        title: '¿Vaciar la papelera?';
      };
      search: {
        all: 'Buscar notas...';
        review: 'Buscar en notas por revisar...';
        trash: 'Buscar en papelera...';
      };
      semantic: {
        noExactMatch: 'No hay coincidencias exactas, pero estas notas son temáticamente similares.';
        noResults: 'Sin resultados.';
        titleNoKeyword: 'Notas temáticamente similares';
        titleWithKeyword: 'Semánticamente similares';
      };
      split: {
        closePaneAria: 'Cerrar este panel';
        closePaneTitle: 'Cerrar panel';
        closeTitle: 'Cerrar panel derecho (⌘\\)';
        noOtherNotes: 'Sin otras notas disponibles';
        openTitle: 'Abrir nota lado a lado (⌘\\)';
        searchPlaceholder: 'Buscar nota para abrir lado a lado...';
      };
      suggestions: {
        maturity: 'Esta nota tiene varias conexiones y un resumen ejecutivo — parece una idea madura.';
        promote: 'Promover a {{type}}';
        promoteDescription: 'La AI detectó que esta nota encaja mejor como {{type}}.';
      };
      tabs: {
        all: 'Todas';
        favorites: 'Favoritas';
        review: 'Por revisar';
        trash: 'Papelera';
      };
      trash: {
        captionDays_many: 'Las notas se eliminan definitivamente a los {{count}} días.';
        captionDays_one: 'Las notas se eliminan definitivamente a {{count}} día.';
        captionDays_other: 'Las notas se eliminan definitivamente a los {{count}} días.';
        captionNever: 'Las notas en papelera no se eliminan automáticamente.';
        change: 'Cambiar';
        empty: 'Vaciar papelera';
      };
      viewAsGraph: 'Ver como grafo';
    };
    objectives: {
      area: 'Área';
      card: {
        expandAria: 'Expandir objetivo';
        hideDetailsAria: 'Ocultar detalles';
        linkProject: 'Vincular proyecto';
        linkProjectOption: '+ Vincular proyecto...';
        noAvailableProjects: '(sin proyectos disponibles)';
        noLinkedProjects: 'Sin proyectos vinculados aún.';
        progress_many: '{{percent}}% completado · {{count}} proyectos';
        progress_one: '{{percent}}% completado · {{count}} proyecto';
        progress_other: '{{percent}}% completado · {{count}} proyectos';
        unlinkAria: 'Desvincular proyecto';
      };
      createFirst: 'Crear primer objetivo';
      deadline: {
        none: 'Sin deadline';
        overdue_many: '{{date}} · vencido hace {{count}} días';
        overdue_one: '{{date}} · vencido hace {{count}} día';
        overdue_other: '{{date}} · vencido hace {{count}} días';
        today: '{{date}} · hoy';
        tomorrow: '{{date}} · mañana';
        upcoming_many: '{{date}} · faltan {{count}} días';
        upcoming_one: '{{date}} · falta {{count}} día';
        upcoming_other: '{{date}} · faltan {{count}} días';
      };
      deadlineOptional: 'Deadline (opcional)';
      empty: 'Sin objetivos aún';
      emptyHint: 'Crea tu primer objetivo para empezar a medir progreso.';
      name: 'Nombre';
      namePlaceholder: 'Lanzar MVP...';
      new: 'Nuevo objetivo';
      noArea: 'Sin área';
      title: 'Objetivos';
    };
    onboarding: {
      checklist: {
        allComplete: '¡Listo! Ya conocés lo esencial de SecondMind.';
        dismissAria: 'Descartar guía de primeros pasos';
        progress: '{{completed}} de {{total}} completados';
        title: 'Primeros pasos';
      };
      steps: {
        apiKey: {
          ctaLabel: 'Configurar';
          description: 'Configurá tu API key de Anthropic para activar la clasificación con IA.';
          label: 'Conectá tu IA';
        };
        firstNote: {
          ctaLabel: 'Crear nota';
          description: 'Empezá a construir tu segundo cerebro con una nota.';
          label: 'Creá tu primera nota';
        };
        firstTask: {
          ctaLabel: 'Crear tarea';
          description: 'Llevá tus ideas a la acción con una tarea.';
          label: 'Creá tu primera tarea';
        };
        inboxAi: {
          ctaLabel: 'Capturar';
          description: 'Capturá una idea y mirá cómo la IA la organiza por vos.';
          label: 'Probá la magia de la IA';
        };
      };
      welcome: {
        description: 'Tu segundo cerebro para capturar ideas, conectar tu conocimiento y dejar que la IA te ayude a organizarlo.';
        pillars: {
          ai: {
            description: 'Clasifica, etiqueta y resume tus capturas automáticamente.';
            title: 'La IA organiza por vos';
          };
          capture: {
            description: 'Tirá ideas al inbox y procesalas después, sin perder el hilo.';
            title: 'Capturá sin fricción';
          };
          connect: {
            description: 'Notas atómicas enlazadas que forman tu segundo cerebro.';
            title: 'Conectá tu conocimiento';
          };
        };
        start: 'Empezar';
        title: 'Te damos la bienvenida a SecondMind';
      };
    };
    projects: {
      area: 'Área';
      createFirst: 'Crear primer proyecto';
      detail: {
        linkNote: 'Vincular nota';
        linkNoteDisabledTitle: 'Crea una nota primero';
        linkNoteEnabledTitle: 'Vincular nota existente';
        linkedNotesHeader: 'Notas vinculadas ({{total}})';
        noTasks: 'Sin tareas aún';
        noTasksHint: 'Crea una tarea arriba para empezar.';
        progress: 'Progreso';
        progressDetail: '{{completed}} de {{total}} tareas completadas ({{percent}}%)';
        tasksHeader: 'Tareas ({{total}})';
      };
      empty: 'Sin proyectos aún';
      emptyHint: 'Crea tu primer proyecto para empezar a agrupar tareas y notas.';
      linkModal: {
        noNotes: 'Sin notas disponibles para vincular';
        noResults: 'Sin resultados';
        searchPlaceholder: 'Buscar notas...';
      };
      name: 'Nombre';
      namePlaceholder: 'Sitio web personal...';
      new: 'Nuevo proyecto';
      noName: '(sin nombre)';
      noPendingTasks: 'Sin tareas pendientes';
      noteList: {
        empty: 'Sin notas vinculadas aún';
        emptyHint: 'Vinculá notas existentes desde el botón de arriba.';
        unlinkAria: 'Desvincular nota';
      };
      pendingTasks_many: '{{count}} tareas pendientes';
      pendingTasks_one: '{{count}} tarea pendiente';
      pendingTasks_other: '{{count}} tareas pendientes';
      priority: 'Prioridad';
      status: 'Estado';
      title: 'Proyectos';
    };
    settings: {
      apiKeys: {
        configured: 'Configurada';
        description: 'Configurá tu propia API key para habilitar la clasificación del inbox y el auto-tagging con IA. Se guarda cifrada y solo la usan tus Cloud Functions.';
        getKeyLink: 'Obtené tu API key en console.anthropic.com';
        help: 'Habilita la clasificación del inbox y el auto-tagging de notas con IA.';
        maskedKey: 'sk-ant-…{{last4}}';
        provider: 'Anthropic (Claude)';
        remove: 'Borrar';
        save: 'Guardar';
        title: 'Proveedores de IA';
        validating: 'Validando…';
      };
      appInfo: {
        changelogLink: 'Ver novedades anteriores';
        checkUpdates: 'Buscar actualizaciones';
        description: 'Versión actual y actualizaciones.';
        platform: {
          android: 'Android';
          desktop: 'Escritorio';
          web: 'Web';
        };
        productName: 'SecondMind Desktop';
        title: 'Información de la app';
        version: 'Versión {{version}}';
      };
      appearance: {
        description: 'Elegí el modo de color. Automático sigue la preferencia del sistema.';
        title: 'Apariencia';
      };
      language: {
        description: 'Elegí el idioma de la interfaz. Los textos generados por la IA siguen esta preferencia.';
        en: {
          description: 'Interface in English.';
          label: 'English';
        };
        es: {
          description: 'La interfaz en español.';
          label: 'Español';
        };
        title: 'Idioma';
      };
      sidebar: {
        description: 'Elegí si el menú lateral aparece o se oculta para maximizar espacio. Aplica solo a pantallas grandes.';
        hidden: {
          description: 'Maximiza espacio. Usá Cmd/Ctrl+B o Cmd/Ctrl+K para navegar.';
          label: 'Oculto';
        };
        title: 'Visibilidad del menú';
        visible: {
          description: 'El menú lateral aparece en pantallas grandes.';
          label: 'Visible';
        };
      };
      subtitle: 'Configuración de cuenta y preferencias.';
      theme: {
        auto: 'Automático';
        dark: 'Oscuro';
        light: 'Claro';
        resolved: {
          dark: 'oscuro';
          light: 'claro';
        };
      };
      title: 'Ajustes';
      trash: {
        days15: {
          description: 'Equilibrio entre tiempo y espacio.';
          label: '15 días';
        };
        days30: {
          description: 'Mantiene las notas el mayor tiempo posible.';
          label: '30 días';
        };
        days7: {
          description: 'Limpieza semanal automática.';
          label: '7 días';
        };
        description: 'Tiempo en la papelera antes de eliminar definitivamente. La limpieza ocurre una vez al día.';
        never: {
          description: 'Las notas eliminadas no se borran nunca solas.';
          label: 'Nunca';
        };
        title: 'Papelera de notas';
      };
    };
    sync: {
      changesPending: 'Cambios sin sincronizar';
      changesUnsaved: 'Cambios sin guardar';
      discard: 'Descartar';
      discardDialog: {
        confirm: 'Descartar todo';
        description: 'Estos cambios se perderán y no se podrán recuperar.';
        title: '¿Descartar cambios pendientes?';
      };
      empty: 'Sin cambios pendientes.';
      errorBadge: 'error';
      openDetail: '{{label}}: abrir detalle';
      pending_many: '{{count}} pendientes';
      pending_one: '{{count}} pendiente';
      pending_other: '{{count}} pendientes';
      popoverTitle: 'Cambios sin sincronizar';
      unsaved_many: '{{count}} sin guardar';
      unsaved_one: '{{count}} sin guardar';
      unsaved_other: '{{count}} sin guardar';
    };
    tasks: {
      card: {
        completeAria: 'Completar tarea';
        date: 'Fecha';
        description: 'Descripción';
        descriptionPlaceholder: 'Agregá notas o detalles...';
        editAria: 'Editar tarea';
        hideDetailsAria: 'Ocultar detalles';
        markPendingAria: 'Marcar pendiente';
        noProject: '(sin proyecto)';
        priority: 'Prioridad';
        project: 'Proyecto';
      };
      empty: {
        completedHint: '¡A darle! Las últimas 20 completadas aparecerán acá.';
        completedTitle: 'Aún no completaste tareas';
        soonHint: 'Las tareas con fecha en los próximos 7 días aparecerán acá.';
        soonTitle: 'Sin tareas próximas';
        todayHint: 'Crea una tarea arriba o revisa el tab “Pronto”.';
        todayTitle: 'Nada para hoy 🎉';
      };
      groups: {
        overdue: 'Vencidas';
        today: 'Hoy';
      };
      newPlaceholder: 'Nueva tarea... (Enter para crear)';
      tabs: {
        completed: 'Completadas';
        soon: 'Pronto';
        today: 'Hoy';
      };
      title: 'Tareas';
    };
    time: {
      justNow: 'hace instantes';
    };
    updateBanner: {
      flushing: 'Sincronizando antes de actualizar…';
      forceUpdate: 'Actualizar igual';
      newVersion: 'Hay una nueva versión disponible.';
      newVersionPending_many: 'Hay una nueva versión disponible ({{count}} cambios pendientes).';
      newVersionPending_one: 'Hay una nueva versión disponible ({{count}} cambio pendiente).';
      newVersionPending_other: 'Hay una nueva versión disponible ({{count}} cambios pendientes).';
      unsynced_many: '{{count}} cambios sin sincronizar.';
      unsynced_one: '{{count}} cambio sin sincronizar.';
      unsynced_other: '{{count}} cambios sin sincronizar.';
      updateNow: 'Actualizar ahora';
      updating: 'Actualizando…';
    };
  };
}
