// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  translation: {
    capture: {
      fabLabel: 'Captura rápida';
    };
    commandPalette: {
      actions: 'Acciones';
      closeSplit: 'Cerrar panel derecho';
      groups: {
        notes: 'Notas';
        projects: 'Proyectos';
        tasks: 'Tareas';
      };
      hideSidebar: 'Ocultar sidebar';
      noResults: 'Sin resultados para “{{query}}”';
      open: 'Abrir buscador';
      openSplit: 'Abrir nota lado a lado';
      placeholder: 'Buscar notas, tareas, proyectos...';
      recent: 'Recientes';
      showSidebar: 'Mostrar sidebar';
      title: 'Buscar';
      trigger: 'Buscar…';
    };
    common: {
      activeBadge: 'activo';
      avatar: 'Avatar';
      cancel: 'Cancelar';
      close: 'Cerrar';
      retry: 'Reintentar';
    };
    dashboard: {
      greeting: {
        afternoon: 'Buenas tardes, {{name}}';
        fallbackName: 'hola';
        morning: 'Buenos días, {{name}}';
        night: 'Buenas noches, {{name}}';
      };
      habitsToday: {
        progress: 'Progreso';
        seeWeek: 'Ver semana →';
        title: 'Hábitos de hoy';
      };
      hubs: {
        connections: 'Hub: {{total}} conexiones';
        empty: 'Linkea notas escribiendo @ — los hubs aparecerán acá.';
        title: 'Hubs activos';
      };
      inbox: {
        empty: 'Inbox limpio 🎉';
        process: 'Procesar →';
        requiresConnection: 'Requiere conexión a internet';
        title: 'Inbox';
      };
      projects: {
        empty: 'Sin proyectos activos';
        noPendingTasks: 'Sin tareas pendientes';
        pendingTasks_many: '{{count}} tareas pendientes';
        pendingTasks_one: '{{count}} tarea pendiente';
        pendingTasks_other: '{{count}} tareas pendientes';
        seeAll: 'Ver todos →';
        seeProjects: 'Ver proyectos →';
        title: 'Proyectos activos';
      };
      recentNotes: {
        createFirst: 'Crear primera nota →';
        empty: 'No tenés notas todavía.';
        seeAll: 'Ver todas →';
        title: 'Notas recientes';
      };
      review: {
        empty: 'Nada que repasar hoy. Vuelve mañana o crea más notas para activar la revisión.';
        seeAll: 'Ver todas las {{total}}';
        titleEmpty: 'Por revisar';
        title_many: 'Te tocan {{count}} notas hoy.';
        title_one: 'Te toca {{count}} nota hoy.';
        title_other: 'Te tocan {{count}} notas hoy.';
      };
      tasks: {
        completeAria: 'Completar {{name}}';
        empty: 'Nada para hoy 🎉';
        seeAll: 'Ver todas →';
        title: 'Tareas de hoy';
      };
    };
    habits: {
      gridHeader: 'Hábito';
      nextWeek: 'Semana siguiente';
      prevWeek: 'Semana anterior';
      title: 'Hábitos';
      today: 'Hoy';
    };
    installPrompt: {
      install: 'Instalar';
      message: 'Instalar SecondMind para acceso directo desde tu dispositivo.';
    };
    nav: {
      ariaMain: 'Navegación principal';
      closeMenu: 'Cerrar menú';
      expandMenu: 'Expandir menú';
      items: {
        dashboard: 'Dashboard';
        graph: 'Grafo';
        habits: 'Hábitos';
        inbox: 'Inbox';
        notes: 'Notas';
        objectives: 'Objetivos';
        projects: 'Proyectos';
        settings: 'Ajustes';
        tasks: 'Tareas';
      };
      openMenu: 'Abrir menú';
      sections: {
        execution: 'Ejecución';
        knowledge: 'Conocimiento';
      };
      showMenu: 'Mostrar menú';
      signOut: 'Cerrar sesión';
    };
    settings: {
      apiKeys: {
        configured: 'Configurada';
        description: 'Configurá tu propia API key para habilitar la clasificación del inbox y el auto-tagging con IA. Se guarda cifrada y solo la usan tus Cloud Functions.';
        getKeyLink: 'Obtené tu API key en console.anthropic.com';
        help: 'Habilita la clasificación del inbox y el auto-tagging de notas con IA.';
        maskedKey: 'sk-ant-…{{last4}}';
        provider: 'Anthropic (Claude)';
        remove: 'Borrar';
        save: 'Guardar';
        title: 'Proveedores de IA';
        validating: 'Validando…';
      };
      appInfo: {
        checkUpdates: 'Buscar actualizaciones';
        description: 'Versión actual y actualizaciones.';
        productName: 'SecondMind Desktop';
        title: 'Información de la app';
        version: 'Versión {{version}}';
      };
      appearance: {
        description: 'Elegí el modo de color. Automático sigue la preferencia del sistema.';
        title: 'Apariencia';
      };
      language: {
        description: 'Elegí el idioma de la interfaz. Los textos generados por la IA siguen esta preferencia.';
        en: {
          description: 'Interface in English.';
          label: 'English';
        };
        es: {
          description: 'La interfaz en español.';
          label: 'Español';
        };
        title: 'Idioma';
      };
      sidebar: {
        description: 'Elegí si el menú lateral aparece o se oculta para maximizar espacio. Aplica solo a pantallas grandes.';
        hidden: {
          description: 'Maximiza espacio. Usá Cmd/Ctrl+B o Cmd/Ctrl+K para navegar.';
          label: 'Oculto';
        };
        title: 'Visibilidad del menú';
        visible: {
          description: 'El menú lateral aparece en pantallas grandes.';
          label: 'Visible';
        };
      };
      subtitle: 'Configuración de cuenta y preferencias.';
      theme: {
        auto: 'Automático';
        dark: 'Oscuro';
        light: 'Claro';
        resolved: {
          dark: 'oscuro';
          light: 'claro';
        };
      };
      title: 'Ajustes';
      trash: {
        days15: {
          description: 'Equilibrio entre tiempo y espacio.';
          label: '15 días';
        };
        days30: {
          description: 'Mantiene las notas el mayor tiempo posible.';
          label: '30 días';
        };
        days7: {
          description: 'Limpieza semanal automática.';
          label: '7 días';
        };
        description: 'Tiempo en la papelera antes de eliminar definitivamente. La limpieza ocurre una vez al día.';
        never: {
          description: 'Las notas eliminadas no se borran nunca solas.';
          label: 'Nunca';
        };
        title: 'Papelera de notas';
      };
    };
    sync: {
      changesPending: 'Cambios sin sincronizar';
      changesUnsaved: 'Cambios sin guardar';
      discard: 'Descartar';
      discardDialog: {
        confirm: 'Descartar todo';
        description: 'Estos cambios se perderán y no se podrán recuperar.';
        title: '¿Descartar cambios pendientes?';
      };
      empty: 'Sin cambios pendientes.';
      errorBadge: 'error';
      openDetail: '{{label}}: abrir detalle';
      pending_many: '{{count}} pendientes';
      pending_one: '{{count}} pendiente';
      pending_other: '{{count}} pendientes';
      popoverTitle: 'Cambios pendientes de sincronizar';
      unsaved: '{{count}} sin guardar';
      unsaved_many: '{{count}} sin guardar';
      unsaved_one: '{{count}} sin guardar';
      unsaved_other: '{{count}} sin guardar';
    };
    time: {
      justNow: 'hace instantes';
    };
    updateBanner: {
      flushing: 'Sincronizando antes de actualizar…';
      forceUpdate: 'Actualizar igual';
      newVersion: 'Hay una nueva versión disponible.';
      newVersionPending_many: 'Hay una nueva versión disponible ({{count}} cambios pendientes).';
      newVersionPending_one: 'Hay una nueva versión disponible ({{count}} cambio pendiente).';
      newVersionPending_other: 'Hay una nueva versión disponible ({{count}} cambios pendientes).';
      unsynced_many: '{{count}} cambios sin sincronizar.';
      unsynced_one: '{{count}} cambio sin sincronizar.';
      unsynced_other: '{{count}} cambios sin sincronizar.';
      updateNow: 'Actualizar ahora';
      updating: 'Actualizando…';
    };
  };
}
